### ISSUE TITLE
Stable or Devel?

### ISSUE THREAD

**Issue by fluorescent-haze** [kiss-community/community#1098]
I've noticed that some packages are kept at a stable version, and some at the development version. It seems this kind of thing is left up to the developers discretion.

I suggest all packages be kept at a stable version, unless there's a good reason not to do so. If that is the case, a comment should be left in the `version` file, justifying the decision for any future maintainers (lines after the first one are ignored by `kiss`, making them suitable for comments.

**Comment by dilyn-corner** [comment]
Why?

May 25, 2022, 1:06 PM by ***@***.***:

**Comment by git-bruh** [comment]
Can you list the packages using dev versions?

**Comment by fluorescent-haze** [comment]
> Can you list the packages using dev versions?

- busybox 1.35.0 (unstable)
- mesa 22.1.0 (dev release)
- mpv git (master branch)

These all seem to be from the unofficial `repo`, not `community`.

To clarify when I said "dev" version, I really meant "not stable", so dev, unstable, prelease, etc. fall under that category.

**Comment by fluorescent-haze** [comment]
> Why?

Because from my perspective, the benefits of using unstable versions (new features) don't outweigh the costs (higher prevalence of bugs).

I'm not dogmatically opposed to it, just that stable should be the norm, and using *unstable* should be done for a good reason, in which case it should be specified, as I already said above.

**Comment by dilyn-corner** [comment]
> Because from my perspective, the benefits of using unstable versions (new features) don't outweigh the costs (higher prevalence of bugs).

KISS is a (by default) rolling-release distribution. If users have a problem with this, there is an easy solution: fork the package. `kiss fork` & `kiss link` make this trivial.

> just that stable should be the norm

Why?

> using unstable should be done for a good reason, 

is "because KISS is rolling & the maintainer chose this release" not a good reason?

> in which case it should be specified,

It is specified; it isn't perhaps *obvious* (`-dev`, `-git`, etc), but the `version` file tells you everything you have to know.
That packages will be very close to `main` or exactly `main` is encoded in the fact that KISS is rolling.



If there are bugs, they should be reported. If you don't want to be a bug tester, (1) don't use rolling, or (2) fork the package.

**Comment by fluorescent-haze** [comment]
I'm closing this issue, because it seems most people are fine with things as is, and frankly, it's not that big of a deal for me either. Most packages use stable versions anyway.
