### ISSUE TITLE
kakoune: fix build

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/community#1131]
@riteo kakoune needs a patch to fix constexpr usage: http://0x0.st/oSLn.patch

**Comment by Riteo** [comment]
Oh right, I procrastinated on it and forgot it completely. I didn't know anybody except me used Kakoune here lol. That got fixed upstream long ago, it got caused by a new compiler release or something like that IIRC, but mawww hasn't released a new version in months. I applied the patch but I think that we should switch to a later commit or to a git version completely as we're missing quite a lot of work (eg. a hare syntax highlighter) and while reading the issue tracker it looks like that the more "advanced" users should just compile the head of the main branch. Thanks a lot for the patch!
