### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by dilyn-corner** [kiss-community/community#733]
Some I've found:

~`libseccomp` requires `linux-headers make` @sdsddsd1~
~`squashfs-tools` requires `lzo` @git-bruh~

**Comment by dilyn-corner** [comment]
`nettle` requires `m4` @git-bruh

**Comment by Vouivre** [comment]
@dilyn-corner  Are you sure about `gnutls` ? I was able to build it without `linux-headers`.

**Comment by dilyn-corner** [comment]
:thinking: I don't know how to explain it. I may very well just be misremembering which package it was, but you're correct.

**Comment by Vouivre** [comment]
It leads to another question: I will never see that `linux-headers` is a dependency, because when I create a package I test it in a chroot with a minimal installation. So with every packages from `core`. 

In this case, I uninstalled `linux-headers` to test, which I never do. `make` for example could be a dependency for a lot of packages, but because it's in `core`, it's never a dependency. So which packages from `core` could be listed
as a dependency of another package ? Or if the list is shorter: which packages will never be listed as a dependency in `core` ?

**Comment by dilyn-corner** [comment]
Things that should not be listed as dependencies: 
```
make
gcc
binutils
musl
busybox
```

We assume users have a toolchain (compiler, linker, libc) for building packages from source, and we assume they have some usable core utilities (`busybox`).

**Comment by Vouivre** [comment]
What about `pigz` and `xz` ? We need some tools to extract and they are not in `busybox`.

**Comment by dilyn-corner** [comment]
Unless something specifically relies on an extraction method not supported by `kiss` (see `iosevka-nerd-fonts` & `zip`) OR specifically requires those libraries (if you built `zstd` with `lzma` support, for instance), there's no real need to mention these packages. `zstd` can theoretically provide almost every extraction function, and there are usually adequate alternatives you shouldn't assume (`zlib` vs `zlib-ng`, `gzip` vs `pigz`, etc). 

Nov 27, 2021, 11:03 AM by ***@***.***:

**Comment by Vouivre** [comment]
Thank you!
